module.exports.descriptors = [
    "Chill",
    "Fun",
    "Cute",
    "Romantic",
    "Vibey",
    "Adventurous",
    "Picturesque",
    "Trendy",
    "Pretty",
    "Thrilling",
    "Beautiful",
    "Pretty",
    "Artsy",
    "Unique",
    "Classic",
    "Local",
    "City",
    "Country"
]

module.exports.places = [
    "Restaurant",
    "Library",
    "Park",
    "Museum",
    "Place",
    "Dessert Spot",
    "Movie Theatre",
    "Concert",
    "Event",
    "Coffee Shop",
    "Hiking Trail",
    "Campground",
    "Mini Golf",
    "Bowling Alley",
    "Dance",
    "Fair",
    "Festival",
    "Store",
    "Club",
    "Bar",
    "Gym"
]